# Generated by Django 5.1.6 on 2025-03-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('assistente', 'Assistente'), ('analista', 'Analista'), ('coordenador', 'Coordenador')], max_length=20)),
                ('chave', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='chave',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Chave',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
